service: mailtube

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:Get*
        - s3:List*
      Resource: arn:aws:s3:::craiggunson.email/*
    - Effect: Allow
      Action:
        - ses:SendEmail
        - ses:SendRawEmail
      Resource: '*'

#plugins:
  #- serverless-plugin-canary-deployments
functions:
  mailtube:
    handler: handler.email
    environment:
      privateaddress: cbgunson@gmail.com
    #deploymentSettings:
      #type: Linear10PercentEvery1Minute
      #alias: Live

